main_page: https://www.MyStudioURL.com
role_manager_email: Manager@mystudio.academy
role_manager_pass: Mystudio123
role_staff_email: Staff@mystudio.academy
role_staff_pass: Mystudio123
browser: Firefox

